image: mcr.microsoft.com/dotnet/core/sdk:3.1

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID           # Execute jobs in merge request context
    - if: $CI_COMMIT_BRANCH == 'master'  # Execute jobs when a new commit is pushed to master branch

services:
  - mysql:5.7

variables:
  MYSQL_ROOT_PASSWORD: "password"

stages:
  - build
  - test

before_script:
  - apt-get update && apt-get install -y git curl libmcrypt-dev default-mysql-client
  - mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql < sql/comet.account.sql
  - dotnet restore

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test
  script:
    - dotnet test tests/Comet.Account.Tests
    - dotnet test tests/Comet.Core.Tests
    - dotnet test tests/Comet.Network.Tests
