image: microsoft/dotnet:latest

services:
  - mysql:latest

variables:
  MYSQL_ROOT_PASSWORD: password

stages:
  - build
  - test

before_script:
  - apt-get update -q && apt-get install -qqy --no-install-recommends mysql-client
  - dotnet restore

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test
  script:
    - mysql -u root -p\"$MYSQL_ROOT_PASSWORD\" -h mysql < sql/comet.account.sql
    - dotnet test tests/Comet.Account.Tests
    - dotnet test tests/Comet.Core.Tests
    - dotnet test tests/Comet.Network.Tests
